/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package leetcode

import kotlin.test.Test
import kotlin.test.assertTrue
import leetcode.Problem_1299

class Problem_1299_Test {
    @Test fun test() {
        val classUnderTest = Problem_1299()
        assertTrue(classUnderTest.replaceElements(intArrayOf(17, 18, 5, 4, 6, 1)) contentEquals intArrayOf(18, 6, 6, 6, 1, -1))
        
    }
}
