/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package leetcode

import kotlin.test.Test
import kotlin.test.assertEquals
import leetcode.Problem_1304

class Problem_1304_Test {
    @Test fun test() {
        val classUnderTest = Problem_1304()
        assertEquals(classUnderTest.sumZero(10).sum(), 0)
    }
}
