
/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package leetcode

import kotlin.test.Test
import kotlin.test.assertTrue
import leetcode.Problem_1313


class Problem_1313_Test {
    @Test fun test() {
        val classUnderTest = Problem_1313()
        assertTrue(classUnderTest.decompressRLElist(intArrayOf(1,2,3,4)) contentEquals intArrayOf(2,4,4,4))
        assertTrue(classUnderTest.decompressRLElist(intArrayOf(1,1,2,3)) contentEquals intArrayOf(1,3,3))

    }
}

