
/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package leetcode

import kotlin.test.Test
import kotlin.test.assertTrue
import leetcode.Problem_1331


class Problem_1331_Test {
    @Test fun test() {
        val classUnderTest = Problem_1331()
        assertTrue(classUnderTest.arrayRankTransform(intArrayOf(40,10,20,30)) contentEquals intArrayOf(4,1,2,3))
        assertTrue(classUnderTest.arrayRankTransform(intArrayOf(100, 100, 100)) contentEquals intArrayOf(1,1,1))
        assertTrue(classUnderTest.arrayRankTransform(intArrayOf(37,12,28,9,100,56,80,5,12)) contentEquals intArrayOf(5,3,4,2,8,6,7,1,3))
    }
}

