
/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package leetcode

import kotlin.test.Test
import kotlin.test.assertEquals
import leetcode.Problem_1295

class Problem_1295_Test {
    @Test fun test() {
        val classUnderTest = Problem_1295()
        assertEquals(classUnderTest.findNumbers(intArrayOf(12,345,2,6,7896)), 2)
        assertEquals(classUnderTest.findNumbers(intArrayOf(555,901,482,1771)), 1)
        
    }
}

