
/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package leetcode

import kotlin.test.Test
import kotlin.test.assertTrue
import leetcode.Problem_1260


class Problem_1260_Test {
    @Test fun test() {
        val classUnderTest = Problem_1260()
        var grid = arrayOf(
          intArrayOf(1,2,3),
          intArrayOf(4,5,6),
          intArrayOf(7,8,9)
        )
        var k = 1
        var expectRet = listOf(
          listOf(9, 1, 2),
          listOf(3, 4, 5),
          listOf(6, 7, 8)
        )
        var actualRet = classUnderTest.shiftGrid(grid, k)
        assertTrue(actualRet.flatten().toIntArray() contentEquals expectRet.flatten().toIntArray())

        grid = arrayOf(
          intArrayOf(3,8,1,9),
          intArrayOf(19,7,2,5),
          intArrayOf(4,6,11,10),
          intArrayOf(12,0,21,13)
        )
        k = 4
        expectRet = listOf(
          listOf(12,0,21,13),
          listOf(3,8,1,9),
          listOf(19,7,2,5),
          listOf(4,6,11,10)
        )
        actualRet = classUnderTest.shiftGrid(grid, k)
        assertTrue(actualRet.flatten().toIntArray() contentEquals expectRet.flatten().toIntArray())

        grid = arrayOf(
          intArrayOf(1,2,3),
          intArrayOf(4,5,6),
          intArrayOf(7,8,9)
        )
        k = 9
        expectRet = listOf(
          listOf(1,2,3),
          listOf(4,5,6),
          listOf(7,8,9)
        )
        actualRet = classUnderTest.shiftGrid(grid, k)
        assertTrue(actualRet.flatten().toIntArray() contentEquals expectRet.flatten().toIntArray())
    }
}

