
/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package leetcode

import kotlin.test.Test
import kotlin.test.assertEquals
import leetcode.Problem_1281

class Problem_1281_Test {
    @Test fun test() {
        val classUnderTest = Problem_1281()
        assertEquals(classUnderTest.subtractProductAndSum(234), 15)
        assertEquals(classUnderTest.subtractProductAndSum(4421), 21)
        
    }
}

