
/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package leetcode

import kotlin.test.Test
import kotlin.test.assertEquals
import leetcode.Problem_1266

class Problem_1266_Test {
    @Test fun test() {
        val classUnderTest = Problem_1266()
        var points = arrayOf(
          intArrayOf(1, 1), intArrayOf(3, 4), intArrayOf(-1, 0)
        )
        assertEquals(classUnderTest.minTimeToVisitAllPoints(points),7)
        points = arrayOf(
          intArrayOf(3, 2), intArrayOf(-2, 2)
        )
        assertEquals(classUnderTest.minTimeToVisitAllPoints(points),5)
        
    }
}

