
/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package leetcode

import kotlin.test.Test
import kotlin.test.assertEquals
import leetcode.Problem_1332


class Problem_1332_Test {
    @Test fun test() {
        val classUnderTest = Problem_1332()

        assertEquals(classUnderTest.removePalindromeSub("bbaabaaa"), 2);
        assertEquals(classUnderTest.removePalindromeSub("ababb"), 2);
        assertEquals(classUnderTest.removePalindromeSub("ababa"), 1);
        assertEquals(classUnderTest.removePalindromeSub("abb"), 2);
        assertEquals(classUnderTest.removePalindromeSub("baabb"), 2);
    }
}

